### ISSUE TITLE
Request Goerli gETH here!

### ISSUE THREAD

**Issue by mrspcbr** [mrspcbr/github-goerli-faucet#1]
Enter Testnet Wallet as a reply to this comment and **follow me on GitHub** to receive upto **1 gETH per person**. If you require more, a valid reason must be provided.

**Multiple requests can be made in an interval of 1 day.**

**Comment by ubuntutest** [comment]
0x50d73cf9E034800d075Cd3162ee2A911c848b97b

**Comment by mrspcbr** [comment]
> 0x50d73cf9E034800d075Cd3162ee2A911c848b97b

Sent. 

Txn: https://goerli.etherscan.io/tx/0xf5cc9bd0c6d8ddabb5a1dbaa322a15b0ee645f55fcd2fad0d4351a42e609f469

**Comment by mrspcbr** [comment]
> 0x05Bc4d1136D3bFb459e8a06b8c537ce2870debDd

Sent.

Txn: https://goerli.etherscan.io/tx/0xa28600d5990f6c95f057c56db2476c13e4c5b03841c8dda0940e1eb730f1fd86

**Comment by rajenpvp** [comment]
0xbb9f6Fc0Ad1a16CF202C7B4a2fAEf6f3b99e15DA

I followed you sir.

**Comment by skarard** [comment]
0x859010BaAD3E7f51A5EF1e43550056ea29542Fb0

**Comment by yogatdc** [comment]
0x5205601b3e60253a803c44fD258c0d1e949C8161

**Comment by MacMemezie** [comment]
0x9BBfb0F9D0f78D82b2b12D2Ca588a3Be439d4548

idk what happened to the goerli network late last night but gwei spiked and hasnt really come down so this is super helpful.  Thank you :)

**Comment by Agilulfo1820** [comment]
0x52eB606f94091A2BA4f985D98C62880a9BA591B6

**Comment by realsyedshah** [comment]
0xC3048079040C993818021e955b62102094cd4d03

Will def be needing this in future. Ty!

**Comment by zkjet** [comment]
> Enter Testnet Wallet as a reply to this comment and **follow me on GitHub** to receive upto **1 gETH per person**. If you require more, a valid reason must be provided.
> 
> **Multiple requests can be made in an interval of 1 day.**

Starting class for a second solidity boot and we really needed it in the beginning. Also wanting to setup a (working) faucet as well. 
0x7f84f44127F4337a16820321658903c01F06D622

**Comment by mymofcl** [comment]
0xe72038Cc6f181a1Ef4cCb98e020B45D2bE8E7e9d

**Comment by MohabGamal** [comment]
0x7019d3Cc0a363c30d0D31bF55cC6351c78f09A50

**Comment by RzWojtek** [comment]
Hello, I need 50 Goerli ETH for testing, thank you very much.
0x2A05A76b4a2290a63214A32ffe2504D814b348F9

**Comment by RzWojtek** [comment]
I followed :)

**Comment by mattstam** [comment]
0x34f845773D4364999f2fbC7AA26ABDeE902cBb46

Thanks in advance!

**Comment by devNamedKiki** [comment]
0x65f028660Bea474E9Fd923B811Ce2ae5b15f643d

Thanks!

**Comment by mrspcbr** [comment]
> 0xbb9f6Fc0Ad1a16CF202C7B4a2fAEf6f3b99e15DA

Sent.

Txn: https://goerli.etherscan.io/tx/0xd4081b06508937875b60a9612b30e5da6621eef1a85aa46a5ea8a866c0be2a8d

**Comment by mrspcbr** [comment]
> 0x859010BaAD3E7f51A5EF1e43550056ea29542Fb0
> 
> Followed, and I'd really appreciate 10 goerli ETH to share out between our team @ http://massless.io. Or I can send a list of 10 wallet addresses for the other team members?

Sent

Txn: https://goerli.etherscan.io/tx/0x21de1e18b8f84789d666d43e6394e6e9e1e7e77073aaf0f7e533c59fee57ecb1

**Comment by mrspcbr** [comment]
> 0x5205601b3e60253a803c44fD258c0d1e949C8161

Sent.

Txn: https://goerli.etherscan.io/tx/0x040f9c0e54f7f44cded0aacfe9b6677b12f29fd63740ff4aefaa9cd6485a8910

**Comment by mrspcbr** [comment]
> 0x9BBfb0F9D0f78D82b2b12D2Ca588a3Be439d4548
> 
> idk what happened to the goerli network late last night but gwei spiked and hasnt really come down so this is super helpful. Thank you :)

Sent.

Txn: https://goerli.etherscan.io/tx/0xcb0f469099b0e8130d49eb002349a4c94a45c85c404167d3d7d22c1fa1af6250

**Comment by mrspcbr** [comment]
> 0x52eB606f94091A2BA4f985D98C62880a9BA591B6

Sent.

Txn: https://goerli.etherscan.io/tx/0xebb3044e87b27436726ef060fb02463af9bf9f259f8f3003fa11af521e8535fa

**Comment by mrspcbr** [comment]
> 0xC3048079040C993818021e955b62102094cd4d03

Sent.

Txn: https://goerli.etherscan.io/tx/0xe4b5218a164d8724dcbaf9fe098864f8dbfeb62b3062e6f30460f248b63f179e

**Comment by mrspcbr** [comment]
> > Enter Testnet Wallet as a reply to this comment and **follow me on GitHub** to receive upto **1 gETH per person**. If you require more, a valid reason must be provided.
> > **Multiple requests can be made in an interval of 1 day.**
> 
> Starting class for a second solidity boot and we really needed it in the beginning. Also wanting to setup a (working) faucet as well. 0x7f84f44127F4337a16820321658903c01F06D622

Sent 5 gETH.

Txn: https://goerli.etherscan.io/tx/0x883a3fef14beed91a9d608d8a38d530cc5c4de66d0eccc4513e206a4610a9d0e

**Comment by mrspcbr** [comment]
> 0xe72038Cc6f181a1Ef4cCb98e020B45D2bE8E7e9d

Sent.

Txn: https://goerli.etherscan.io/tx/0x56171d4387a1e707eca4c5cbcd10942fe8227d27eae0bb5eea20df7da75105cb

**Comment by mrspcbr** [comment]
> 0x7019d3Cc0a363c30d0D31bF55cC6351c78f09A50

Sent.

Txn: https://goerli.etherscan.io/tx/0x7feaa27f53e89831e9100e0f728956a2bf219fbe09c5d36ffd1c4a9bb4b61f21

**Comment by mrspcbr** [comment]
> 0x41c5848576a0755ADc4f2bDFE5D2D14081b4204F
> 
> thanks man

Follow me first.

**Comment by mrspcbr** [comment]
> Hello, I need 50 Goerli ETH for testing, thank you very much. 0x2A05A76b4a2290a63214A32ffe2504D814b348F9

Sent.

Txn: https://goerli.etherscan.io/tx/0xb34ee578342587f1fa0e4f49d30e582ee24693924a4d978fa259eba81db550ea

**Comment by mrspcbr** [comment]
> 0x34f845773D4364999f2fbC7AA26ABDeE902cBb46
> 
> Thanks in advance!

Follow me first.

**Comment by mrspcbr** [comment]
> 0x65f028660Bea474E9Fd923B811Ce2ae5b15f643d
> 
> Thanks!

Follow me first.

**Comment by napsterly** [comment]
0x89C1Ca055F652f19b17F3D7bdea0F4C52D7d6020 
gracias

**Comment by mrspcbr** [comment]
> I need 5GETH to share between my DAO 0x89C1Ca055F652f19b17F3D7bdea0F4C52D7d6020 gracias

Sent.

Txn: https://goerli.etherscan.io/tx/0xa9e97a9f1913eff4df74aaf48ee567614c817d4b4288a65b853638dd18e7e064

**Comment by Jundullah125** [comment]
> Enter Testnet Wallet as a reply to this comment and **follow me on GitHub** to receive upto **1 gETH per person**. If you require more, a valid reason must be provided.
> 
> **Multiple requests can be made in an interval of 1 day.**

0x5bc73DE284606d3574E3948D7281926af45049b1


Pls I need 100 GETH to share between my DAO...Thanks

**Comment by mrspcbr** [comment]
> > Enter Testnet Wallet as a reply to this comment and **follow me on GitHub** to receive upto **1 gETH per person**. If you require more, a valid reason must be provided.
> > **Multiple requests can be made in an interval of 1 day.**
> 
> 0x5bc73DE284606d3574E3948D7281926af45049b1
> 
> Pls I need 100 GETH to share between my DAO...Thanks

100 ETH is too much to drop. I need to accomadate everyone.

**Comment by mrspcbr** [comment]
> 0x4C2e8c59B422EBD2c46C8fCEB4df4f4Cdc0b2C67 Thank you :')

Sent.

Txn: https://goerli.etherscan.io/tx/0xc4aeec2637b79c8df2e7d0be4802d484567f82dec9e34a6f29f75be435fb4426

**Comment by zslashy** [comment]
0xC4499233D1D625F5e1c4CC25888bb19eD789719d

**Comment by alish536** [comment]
> Enter Testnet Wallet as a reply to this comment and **follow me on GitHub** to receive upto **1 gETH per person**. If you require more, a valid reason must be provided.
> 
> **Multiple requests can be made in an interval of 1 day.**

0x0bE744afF3BF8876d1Ee1DbE61c79DDF5A64696b

**Comment by alish536** [comment]
0x0bE744afF3BF8876d1Ee1DbE61c79DDF5A64696b

**Comment by Beljhit** [comment]
0x8B0be674B79e406F15455C6f98d14ebe301d7f11

Thanks

**Comment by weLuter** [comment]
0x4fA8F80eD782A4c128010F3410b7aa82E0833931
Thanks!

**Comment by n4ru** [comment]
0x B4683485899A654F9DE413FCfDA6ac39d1eB383E

**Comment by shidaxi** [comment]
0x34e17BaAdec22651c5d0080042C216cbebe237bE
64 GoerliETH for 2 validators. Appreciate very much!

**Comment by rawson212** [comment]
0xBBE14fAddCd9535b57A61f43FD3A595CF0F94274

**Comment by chattertechno** [comment]
0x9E6F67AfC6D04BEF244627550e1EB5F2AFE2E449

Just need 3 ETH

**Comment by gianluigi1961** [comment]
0x9bcfdeD4a7B9c51a328c91336F28B2996181E00d

Just need 2 ETH for testing my smart contracts
thanks
Gianluigi

**Comment by alabscrypto** [comment]
0xd92ac1558cD45bD98225d173153bA55c9ef78f9B

**Comment by alabscrypto** [comment]
I just need five please 🙏🏽🙏🏽

0xd92ac1558cD45bD98225d173153bA55c9ef78f9B

**Comment by minoraw77** [comment]
0x4aE37ACF320aD3f540a6506f4f8fcF731DFF5b74

this is a great opportunity to get started with dapp

**Comment by wdcs-LathiyaBhavin** [comment]
> 

Hello i want 20 GETH. struggling for testing one of my important project.

**Comment by benrod3k** [comment]
> > 0x41c5848576a0755ADc4f2bDFE5D2D14081b4204F
> > thanks man
> 
> Follow me first.

Just followed.

**Comment by easydomi** [comment]
0x8e07D2D51F5a9e4B3C7A5068c9C20b2Dc15223A3
Thanks in advance! :)

**Comment by Agus0345** [comment]
plis sendmy 1 goerli sir 0x9a4C49c26b5Cb4c2e399d3Ad31B6E76CCAE00A68

**Comment by gt-del** [comment]
> Enter Testnet Wallet as a reply to this comment and **follow me on GitHub** to receive upto **1 gETH per person**. If you require more, a valid reason must be provided.
> 
> **Multiple requests can be made in an interval of 1 day.**

0x2503C5eb1A421928a807e92529Ff8ce5e2992b4E    thanks

**Comment by Agus0345** [comment]
admin please send me 1 goerli eth I want to join the onomy testnet onomy protocol airdrop all day I'm looking for only 0.1 goerli eth

**Comment by Agus0345** [comment]
> > Enter Testnet Wallet as a reply to this comment and **follow me on GitHub** to receive upto **1 gETH per person**. If you require more, a valid reason must be provided.
> > **Multiple requests can be made in an interval of 1 day.**
> 
> 0x2503C5eb1A421928a807e92529Ff8ce5e2992b4E thanks

please send me 1 goerli eth I want to join the onomy testnet onomy protocol airdrop all day I'm looking for only 0.1 goerli eth

**Comment by Agus0345** [comment]
> Enter Testnet Wallet as a reply to this comment and **follow me on GitHub** to receive upto **1 gETH per person**. If you require more, a valid reason must be provided.
> 
> **Multiple requests can be made in an interval of 1 day.**

0x9a4C49c26b5Cb4c2e399d3Ad31B6E76CCAE00A68

**Comment by mrspcbr** [comment]
> 0xC4499233D1D625F5e1c4CC25888bb19eD789719d Thanks!

Sent.

Txn: https://goerli.etherscan.io/tx/0x8ab8e6c18bf32f61d24838bb42a3ce41d1c4d248fd0b93f57029b555de0086ec

**Comment by mrspcbr** [comment]
> 0x0bE744afF3BF8876d1Ee1DbE61c79DDF5A64696b

Sent.

Txn: https://goerli.etherscan.io/tx/0x9b51cf2807256b2064c2a0a8a8b2189380767b03ab554d27db31351e6d5c77c0

**Comment by mrspcbr** [comment]
> 0x8B0be674B79e406F15455C6f98d14ebe301d7f11
> 
> Thanks

Sent.

Txn: https://goerli.etherscan.io/tx/0x7d6d253a4b64516a1b3b8ea5f2e4dc8616bf20c980586bc00b4c3073293d1285

**Comment by mrspcbr** [comment]
> 0x34e17BaAdec22651c5d0080042C216cbebe237bE

Sent.

Txn: https://goerli.etherscan.io/tx/0x0b1113dd4a9d242e5761d7f46a5b297f68c45d4b551770fb74f8b86dbc4f857a

**Comment by mrspcbr** [comment]
> 0x34e17BaAdec22651c5d0080042C216cbebe237bE 64 GoerliETH for 2 validators please. I followed you, thank you very much!

Sent.

Txn: https://goerli.etherscan.io/tx/0x030af34c66c896faf1d951d0cd9f6ab0f1083bc84e44b3ba704b00b09a98b23b

**Comment by Agus0345** [comment]
> > 0x34e17BaAdec22651c5d0080042C216cbebe237bE 64 GoerliETH for 2 validators please. I followed you, thank you very much!
> 
> Sent.
> 
> Txn: https://goerli.etherscan.io/tx/0x030af34c66c896faf1d951d0cd9f6ab0f1083bc84e44b3ba704b00b09a98b23b

send my 3 goerli thanks 
0x9a4C49c26b5Cb4c2e399d3Ad31B6E76CCAE00A68

**Comment by mrspcbr** [comment]
> 0x9E6F67AfC6D04BEF244627550e1EB5F2AFE2E449

Sent.

Txn: https://goerli.etherscan.io/tx/0x42e23921eb45f5517edfcf47ad1a900c851cdd101142a15e3eed08367457026b

**Comment by mrspcbr** [comment]
> 0x9bcfdeD4a7B9c51a328c91336F28B2996181E00d
> 
> Just need 2 ETH for testing my smart contracts thanks Gianluigi

Sent.

Txn: https://goerli.etherscan.io/tx/0xff67e660707e5578d5f3e2fcd9ac9566e0b77c7349d42df609d571f663b87717

**Comment by mrspcbr** [comment]
> 0x4aE37ACF320aD3f540a6506f4f8fcF731DFF5b74
> 
> this is a great opportunity to get started with dapp

Sent.

Txn: 0x74ad2bf09a1c7fb7170f89609e231e603e1cb5247b02c3d3ced4bc82ec989828

**Comment by mrspcbr** [comment]
> wdcs-LathiyaBhavin

Sent.

Txn: 0xb55698a58a00c63a8811d9edd8d1115e43c7297f8f2134b8bd20a372d1418190

**Comment by mrspcbr** [comment]
> 0x41c5848576a0755ADc4f2bDFE5D2D14081b4204F

Sent.

Txn: 0xe8195ef4f3df0c9db83e4a2ab1bfc38e1dd33ee7c79d7079ba310d77ae0c027f

**Comment by mrspcbr** [comment]
> 0x8e07D2D51F5a9e4B3C7A5068c9C20b2Dc15223A3 Thanks in advance! :)

Sent.

Txn: 0x28f8ef8f1c65cc7936d5fbc0f24417d4f985a6d49f2939fb892235dcc23588ef

**Comment by mrspcbr** [comment]
> 0x9a4C49c26b5Cb4c2e399d3Ad31B6E76CCAE00A68

Sent. 

Txn: 0xcaa0415bf327d42f92171a7b1b39b816c5641c2633da2f130f5419f75fe1bb4c

**Comment by mrspcbr** [comment]
> 0x2503C5eb1A421928a807e92529Ff8ce5e2992b4E

Sent.

Txn: 0xe6305cdf691a3d0ae2b18aea1db203ae3cca5da98ff7a9f643ea7288867d0366

**Comment by mrspcbr** [comment]
> 0x9a4C49c26b5Cb4c2e399d3Ad31B6E76CCAE00A68

Sent 3 ETH.

Txn: 0xdd8d0fc883f9c9f636ddfafd5e91cb3afbb947853a9b6c4dba73f31f024d15b6

**Comment by Agus0345** [comment]
> > 0x9a4C49c26b5Cb4c2e399d3Ad31B6E76CCAE00A68
> 
> Sent 3 ETH.
> 
> Txn: 0xdd8d0fc883f9c9f636ddfafd5e91cb3afbb947853a9b6c4dba73f31f024d15b6

thanks

**Comment by guoshijiang** [comment]
0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266

我需要 32 ETH 做测试网的 validator 质押。

**Comment by bradyjoestar** [comment]
0x70997970C51812dc3A010C7d01b50e0d17dc79C8

thanks man

**Comment by mrspcbr** [comment]
> 0x70997970C51812dc3A010C7d01b50e0d17dc79C8
> 
> 32 GoerliETH for 1 validators please. I followed you, thanks man

Sent.

Txn: 0xf0385d88ef5eb7a8de5f18ba452b7a06de834fbb882ff76ea9f124ece6689d89

**Comment by mrspcbr** [comment]
> 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
> 
> I need 32 ETH for testnet validator staking.

Sent.

Txn: 0x88eb060399396aec0c08ae048fa09ac527fe5f5b3d406d57b5d6faa87c513fea

**Comment by XagnarX** [comment]
0xCcfD0893407e3994e1C73D048cAD0F6c3A9C0732

our's team needs some GoerliETH for the doing swap dapp. Thanks

**Comment by Agus0345** [comment]
send my 5 goerli thanks 
0x9a4C49c26b5Cb4c2e399d3Ad31B6E76CCAE00A68

**Comment by guoshijiang** [comment]
0x5F2c19dDF553C3CE73A5F8b9C8A0D73EFDA1C9c9

Oh, My great god. I want to need another 32 ETH to run another validator, I have been followed your twitter(My twitter is seek_web3, If possible, follow me please) and Github, Please give another 32 ETH, Please, Thank you very much!!!

**Comment by songyaoshun** [comment]
0x875F0DE6b6Ed7C9EC01B3f3f06f5397d79d9D599

need 32 GoerliETH for a validator. I followed you, thanks.

**Comment by reza0982** [comment]
I need 5 goerli
0x9a4C49c26b5Cb4c2e399d3Ad31B6E76CCAE00A68

**Comment by mrspcbr** [comment]
> 0xCcfD0893407e3994e1C73D048cAD0F6c3A9C0732

Sent.

Txn: 0xb45b6820c02486b974c7fbfc037f137828b7c6219cfebb92defacbb3d2a02aa4

**Comment by mrspcbr** [comment]
> 0x5F2c19dDF553C3CE73A5F8b9C8A0D73EFDA1C9c9

Sent.

Txn: 0xba87bec5c4690426051594066864a4cbf11a0c7f68c70f325ef90b39d31a2fa6

**Comment by mrspcbr** [comment]
> 0x875F0DE6b6Ed7C9EC01B3f3f06f5397d79d9D599
> 
> need 32 GoerliETH for a validator. I followed you, thanks.

Sent.

Txn: 0x31dc401885d755ce216f31ae0657c3381ce9e0896953b54442fc41488e0d626f

**Comment by reza0982** [comment]
0x9a4C49c26b5Cb4c2e399d3Ad31B6E76CCAE00A68 
need 32 GoerliETH for a validator.

**Comment by tw5428561** [comment]
0x5964a559Dc0F33b5A2bAC7C8Fb13e5bBFC2BdaF1

our's team needs some GoerliETH for the doing Layer2  test. need 60 GoerliETH Thanks

**Comment by reza0982** [comment]
need 32 GoerliETH for a validator. I followed you, thanks.

0x9a4C49c26b5Cb4c2e399d3Ad31B6E76CCAE00A68

**Comment by reza0982** [comment]
need 32 GoerliETH for a validator. I followed you, thanks.

0x9a4C49c26b5Cb4c2e399d3Ad31B6E76CCAE00A68

**Comment by Cris1245** [comment]
> 

Hello mate, I need 32 GoerliETH pls 
I want to be a validator but I do not know where I find it.

0x02124996c4f87839D724A74f51b03EA033041A5D

**Comment by mrspcbr** [comment]
**Faucet has been stopped due to people abusing the system by making fake accounts to request drops.**

**Comment by rojii** [comment]
0xd3cA7F91eE2a25D2b97A244BC46675CEf1941Ec1

**Comment by Cris1245** [comment]
> **Faucet has been stopped due to people abusing the system by making fake accounts to request drops.**

Pls brother, I want to participate in the Network :(
I only get 0.1 per day, and the transaction costs 0.6 around

**Comment by Doc-Pixel** [comment]
Too bad. 

It's nearly impossible to get a couple of test eth on goerli :-(

I understand why and how.

**Comment by mrspcbr** [comment]
> Doc-Pixel

Post your wallet

**Comment by Doc-Pixel** [comment]
Appreciated!
0xB35E31b33eb6d3501dd73913036C087AD6FB290e is my goerli address.
thx!

**Comment by mrspcbr** [comment]
> Appreciated! 0xB35E31b33eb6d3501dd73913036C087AD6FB290e is my goerli address. thx!

How much do you need?

**Comment by Doc-Pixel** [comment]
Just a couple. Would 5 work?
I'm redeploying a couple of projects on goerli now that ropsten is out of fashion ;-)

**Comment by mrspcbr** [comment]
> Just a couple. Would 5 work? I'm redeploying a couple of projects on goerli now that ropsten is out of fashion ;-)

Sent 5.

Txn: https://goerli.etherscan.io/tx/0x408a383e2eabd64c42fc7b26447edd851aba2127ad76059b513834ba90a790df

**Comment by Doc-Pixel** [comment]
> > Just a couple. Would 5 work? I'm redeploying a couple of projects on goerli now that ropsten is out of fashion ;-)
> 
> Sent 5.
> 
> Txn: https://goerli.etherscan.io/tx/0x408a383e2eabd64c42fc7b26447edd851aba2127ad76059b513834ba90a790df

Love it!

Thanks!

**Comment by CrypticDriver** [comment]
0xc44e191c2bbEF4ecE1cD59a8349F215F61122F78

Need 4 GoerliETH to do some security things for our projects, Thanks

**Comment by marretti** [comment]
0xA8944DD1F88EcB2bACc4EE72E69239d21dC4D71d

**Comment by cryptocooldude** [comment]
Hello need 1 GoerliETH to test on various tenet protocols. Thanks in advance

0xe462792fF23d2373159E020b84D2be15ecBE39dc

**Comment by MumuFan** [comment]
0xC356010CA1C9d762D9C657B6b5D003516e16238B

I followed you sir.

**Comment by MumuFan** [comment]
0xC356010CA1C9d762D9C657B6b5D003516e16238B
Need 10 GoerliETH to do some security things for our projects(name is teleport), Thanks

**Comment by thuongtin** [comment]
0x19ac4a4149d55c7fa749095959ab7ad132eb0f15 (thuongtin.eth)
I need gETH for build validator node

**Comment by ArmoredKitty** [comment]
Hi, This is my wallet ID: 0x3861ED2fe6740cB7609DE02dF8E0193957B00032
I need 10 gETH if possible for my project purposes please.  Thank you in advance.

**Comment by AndrewPC610** [comment]
0x7F992A94C2da795ed5CEB0670Dc0c88e6edeE94c

**Comment by iamjoselyn** [comment]
Working on a test blockchain project too. Thanks.

0xe203935eA38a4C13349C5a2A82cCF7EE2ec4E628

**Comment by kladkogex** [comment]
SKALE Labs engineering and QA team needs 100 geth 

Here is the wallet address

0x8a3569FbC6C13Ee28fD6fD1053b40DE9241F3aE1

**Comment by josvromans** [comment]
0x00eF256c967703Ec84acDbeE0b9690D3BbCBd6dC

Just followed! You can be my hero, I am testing my on-chain generative art project

**Comment by Dushyantgoswami** [comment]
0x6A5CF645CAD751340102Ee24d8B6968729e41b60

**Comment by kevinyu600** [comment]
0xdCf1cCBeE0c9bd034EEF2916d8b5EAebCB80Ca99

Please send some...

**Comment by longdt** [comment]
0x80078f5FB17C99485e540FA548379fE60380ffe9

please help me

**Comment by infinnn** [comment]
0x8392C58eE9D9068f3f638A016F707e22600e2cFe

Need some goerli Testnet ETH

**Comment by chattertechno** [comment]
0xb22cd9e52ddF24f9435d3709A1F828bdeB4242bD

Need  5 ETH.
Using to test my DAO smart contracts still.

**Comment by Psychitect** [comment]
> Enter Testnet Wallet as a reply to this comment and **follow me on GitHub** to receive upto **1 gETH per person**. If you require more, a valid reason must be provided.
> 
> **Multiple requests can be made in an interval of 1 day.**

Can I ask for some eth for some testnets? 0xCFCBaf18155EBFB02E7B2a3c0572f30FE5ecA88A

**Comment by nygell17** [comment]
May I please have 1 gETH. Thank you

0xf6367EC77504423c963BEE10a66d03b228bBC34d

**Comment by Mrzhang06** [comment]
I need 10 GoerliETH , Thanks !!!
0xD8Ca9B129B754b0bE6ab3c9282B8a5671cEeF44b

**Comment by VitorioC** [comment]
0x1810bb2Face5711D20F0C5DA104415B96adad122

as much gETH as possible :D

**Comment by BabyGeniusPics** [comment]
0xd08a89B44724a4c943eBE0c0324F073394188E3C

**Comment by fajaritdgi** [comment]
0x5578e187395Aa986A45293d209126B2499a531f2

**Comment by pieronoviello** [comment]
0x50d73cf9E034800d075Cd3162ee2A911c848b97b

**Comment by ubuntutest** [comment]
0x50d73cf9E034800d075Cd3162ee2A911c848b97b

**Comment by rataprens** [comment]
0x99f2b81Ea25b65e5630e14294A90006465500186

**Comment by S4282** [comment]
0xE29bffB7D26803d83F5CB3f49ad94c11F1B9F210

**Comment by 0xlimE** [comment]
Hello mrspcbr.

May I please request some Goerli eth, >5 would be ideal, but I am happy for anything.

I finally have time to go back and work on my ethereum smart contract security platform (see my github https://github.com/0xlimE/contracthacker) 

But since they closed down the ropsten network, I cannot run the platform.

Thanks in advance

0x79Ba6049fBbf99502e1D324de034B7548aE2601d

**Comment by wdcs-DastageerSayed** [comment]
0x9332Fa648A56E2D39855520236A9d12B9b17dEa2

**Comment by matrixzen7** [comment]
> Enter Testnet Wallet as a reply to this comment and **follow me on GitHub** to receive upto **1 gETH per person**. If you require more, a valid reason must be provided.
> 
> **Multiple requests can be made in an interval of 1 day.**

0x1D8893043d5D9e23438E53e489BD4805bAd36075

**Comment by wdcs-LathiyaBhavin** [comment]
Requesting for 30 goerli ETH. requirde for one of the most important project.
0xa799c2b72e25dB4c8Ea8f9D9e7690fac859c5cee

Followed

**Comment by RzWojtek** [comment]
Hello, I need some Goerli ETH for testing. If you would give me more than 10 gETH I would be very grateful, but I will accept any amount.

0x2A05A76b4a2290a63214A32ffe2504D814b348F9

thank you very much.

**Comment by Ckaarraa** [comment]
Bro I need 30+ getH please can you send me as much as you can

0x5e6E3FF816021A2842cF23c36FAeB0019AF7EcB4

**Comment by Appan-doc** [comment]
Hello, I need some Goerli ETH for testing. If you would give me more than  gETH I would be very grateful.thank you very much.
0x0000036c08Feba5F97D1a0289a76901570b298d5

**Comment by Gavine-Gao** [comment]
0x53b4664e2dB10ca50A449417e303882ce6c2Af78

**Comment by greedy-dev** [comment]
0xBB672366950f39cada35eaA98Da92Bdf447b97F2

**Comment by qwdingyu** [comment]
0xed589c182991D797F39cAE2E147c6caEecA20AC7

**Comment by manav650** [comment]
0x532d1069A649f2C0F6e34DB598f10082b0296f20

I am unable to deploy my contracts, cam you send more than 1 gETH please, thanks.
